// Generated by gencpp from file DualRadar/ArbeRadarMsg.msg
// DO NOT EDIT!


#ifndef DUALRADAR_MESSAGE_ARBERADARMSG_H
#define DUALRADAR_MESSAGE_ARBERADARMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <DualRadar/ArbeRadarPoint.h>

namespace DualRadar
{
template <class ContainerAllocator>
struct ArbeRadarMsg_
{
  typedef ArbeRadarMsg_<ContainerAllocator> Type;

  ArbeRadarMsg_()
    : header()
    , point_num(0)
    , points()  {
    }
  ArbeRadarMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point_num(0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _point_num_type;
  _point_num_type point_num;

   typedef std::vector< ::DualRadar::ArbeRadarPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::DualRadar::ArbeRadarPoint_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ArbeRadarMsg_

typedef ::DualRadar::ArbeRadarMsg_<std::allocator<void> > ArbeRadarMsg;

typedef boost::shared_ptr< ::DualRadar::ArbeRadarMsg > ArbeRadarMsgPtr;
typedef boost::shared_ptr< ::DualRadar::ArbeRadarMsg const> ArbeRadarMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::DualRadar::ArbeRadarMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::DualRadar::ArbeRadarMsg_<ContainerAllocator1> & lhs, const ::DualRadar::ArbeRadarMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.point_num == rhs.point_num &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::DualRadar::ArbeRadarMsg_<ContainerAllocator1> & lhs, const ::DualRadar::ArbeRadarMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace DualRadar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dfd96211a618382806a334c44698f92";
  }

  static const char* value(const ::DualRadar::ArbeRadarMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dfd96211a618382ULL;
  static const uint64_t static_value2 = 0x806a334c44698f92ULL;
};

template<class ContainerAllocator>
struct DataType< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DualRadar/ArbeRadarMsg";
  }

  static const char* value(const ::DualRadar::ArbeRadarMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Livox publish pointcloud msg format.\n"
"\n"
"Header header               # ROS standard message header\n"
"uint32 point_num            # Total number of pointclouds\n"
"ArbeRadarPoint[] points     # Pointcloud data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: DualRadar/ArbeRadarPoint\n"
"# ARBE pointcloud format.\n"
"\n"
"uint32 id               # ID\n"
"float32 x               # X axis, unit:m\n"
"float32 y               # Y axis, unit:m\n"
"float32 z               # Z axis, unit:m\n"
"float32 rcs             # reflectivity, 0~255\n"
"float32 doppler         # livox tag\n"
"\n"
"\n"
;
  }

  static const char* value(const ::DualRadar::ArbeRadarMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point_num);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArbeRadarMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DualRadar::ArbeRadarMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::DualRadar::ArbeRadarMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point_num: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.point_num);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::DualRadar::ArbeRadarPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUALRADAR_MESSAGE_ARBERADARMSG_H
